import pandas adn numpy library

In [1]:
import pandas as pd
import numpy as np

import data

In [2]:
! wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

--2026-09-18 23:32:55--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.04s

2026-09-18 23:32:55 (14.5 MB/s) - ‘car_fuel_efficiency_2026.csv’ saved [635180/635180]

DataFrame

In [3]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  object
 2   fuel_type            10000 non-null  object
 3   drivetrain           10000 non-null  object
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), object(3)
memory usage: 859.5+ KB

In [5]:
df.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

Q1. What version of Pandas did you install?

In [6]:
pd.__version__ # Pandas version is 2.2.3

'2.2.3'

Q2. Records count: How many records are in the dataset?

In [7]:
print(df.shape) # 10,000 rows and 11 columns

(10000, 11)

Q3. Fuel types: How many fuel types are presented in the dataset?

In [8]:
df['fuel_type'].unique() # 3 difference type of fuel

array(['Gasoline', 'Diesel', 'Hybrid'], dtype=object)

Q4. Missing values: How many columns in the dataset have missing values?

In [9]:
null_value = df.isnull().sum()
null_value # 877 missing value in horsepower and 264 missing vaue in acceleration columns

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [10]:
(null_value > 0).sum() # total 2 columns have missing values

np.int64(2)

Q5. Max fuel efficiency: What's the maximum fuel efficiency of cars from Asia?

In [11]:
df[df["origin"] == "Asia"]["fuel_efficiency_mpg"].max() # Maximum fuel efficiency of cars from Asia is 41.2

41.2

Q6. Median value of horsepower

In [12]:
horse_power = df['horsepower'].median()
print('Median value of the horsepower = ',horse_power) # Find the median value of the horsepower column in the dataset.

Median value of the horsepower =  254.0

In [13]:
horsepower_mode = df['horsepower'].mode()
print('Mode value of the horsepower = ',horsepower_mode) # Calculate the most frequent value of the same horsepower column.

Mode value of the horsepower =  0    252.0
Name: horsepower, dtype: float64

In [14]:
horsepower_mode_fillin=df["horsepower"] = df["horsepower"].fillna(df["horsepower"].mode()[0])
print(horsepower_mode_fillin) # Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [15]:
horse_power = df["horsepower"].median()
print("horse power new median =", horse_power) # calculate the median value of horsepower once again.

horse power new median = 252.0

Q7. Sum of weights: What's the sum of all the elements of the result?

In [16]:
df_asia = df[df["origin"] == "Asia"] # Select all the cars from Asia
X = df_asia[["vehicle_weight", "model_year"]] # Select columns vehicle_weight and model_year
X = X.head(7).to_numpy() #Select the first 7 values and Get the underlying NumPy array. Call it X.
print(X)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

In [17]:
XTX = X.T.dot(X) # Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Call the result XTX.
print(XTX)

[[131950500  60750580]
 [ 60750580  28041424]]

In [18]:
XTX_inv = np.linalg.inv(XTX) # Invert XTX.
print(XTX_inv)

[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]

In [19]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200]) # Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
w = XTX_inv.dot(X.T).dot(y) # Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
print(w)

[0.13644777 0.2327492 ]

In [20]:
w.sum() # Sum of all the elements of the result

np.float64(0.36919696904925486)